[package]
name = "ez"
entry = "manifest/manifest.bend"
bin = "ez/main.bend"

[deps.sha256]
hash = "0x33de775bd13bab25b3e2d6f5bbcb8776"
git = "https://github.com/Giulio2002/bend-sha256"
rev = "5887e7cefa273ff7f90e3edfd6e90b815bbc79ed"
root = "."
narHash = "sha256-FLTyFw5HkOrl/T6E8hbs/XVwL05oGmcJARW9I9eHdgA="
vendor = "true"
entry = "sha256.bend"

[deps.shake]
hash = "0xebdf72b20ad527103f6efc0d2aa8f1ec"
git = "https://github.com/Emerging-Patterns/shake"
rev = "3424b39197335f0aa741e8928dbe5c27b3bde0ef"
tag = "v0.1.0"
root = "shake"
narHash = "sha256-JXsEnp4NFlBxM7dNPSCU4TDBuF+d76h5bYgwOd6iu+0="
entry = "shake/main.bend"

[deps.eztoml]
hash = "0x04b9afdd6d6a56039c5ce6dfb1e55294"
git = "https://github.com/Emerging-Patterns/eztoml"
rev = "ea1a73f06cbc2700b5b45dc199b104969527e48a"
tag = "v0.1.0"
root = "eztoml"
narHash = "sha256-lSFpfmFwEHUHT9w0J16Dr6n0PbkKPEYNvVrUOZtMyI8="
entry = "eztoml/main.bend"

[deps.snap]
hash = "0x9bfd9d57916f3439316c2775fd1f10b4"
git = "https://github.com/Emerging-Patterns/snap"
rev = "0ce9a0fd709e5aa819b984b6bacbfb18729d94b0"
root = "snap"
narHash = "sha256-DmpBuSpjZ3WdPAEQzWcS/BjsNxiCXbxRb8tZB0pYh+Q="
entry = "snap/main.bend"

[deps.ezhttp]
hash = "0x4dc5182d578920eeb43d8db11d399d9a"
git = "https://github.com/Emerging-Patterns/ezhttp"
rev = "68419d690f8d81919ae9c7ada1830e10ed31c2ca"
tag = "v0.4.0"
root = "ezhttp"
narHash = "sha256-qZgitdcapYx7uE23KbzWeVIxAjefvNZ6cBh3iSbUyVc="
entry = "ezhttp/main.bend"

[tools.bolt]
git = "https://github.com/Emerging-Patterns/bolt"
rev = "a38e87ac89de11cbabfb083127269e0059ef73f5"
tag = "v0.9.0"
root = "."
narHash = "sha256-xKP9Lc1Eprn4nHTWiNJ85r9aPMGNFIOkvtBBb50DWYo="
