[package]
name = "ez"
entry = "ledger/manifest.bend"
bin = "ez/main.bend"
[deps]
[deps.sha256]
hash = "0xa17f0215fb4dd22e26fd007661489402"
git = "https://github.com/noah-emp/bend-sha256"
rev = "1319f22df2d5072a861cc71740c93258c44ac4ff"
root = "."
narHash = "sha256-XYNpKGNHcpV5vRjFMOSlVVBchSdrpJrxgbGzd4dXXAQ="
entry = "package.bend"
[deps.shake]
hash = "0x085b03c84ca37125e38dddede7b91e55"
git = "https://github.com/Emerging-Patterns/shake"
rev = "ddb93921dea168aed7a37d3e56e00c4732cf9082"
tag = "v0.2.0"
root = "."
narHash = "sha256-o5NRUjz6OBNMecXY8CZzYQpqoGFxdolD/ST8rIgAnLo="
entry = "main.bend"
[deps.snap]
hash = "0xabe575924687afad4cee1a2c1194d639"
git = "https://github.com/Emerging-Patterns/snap"
rev = "fcabc81830c9e21d86d4968810285b287da49c12"
tag = "v1.1.0"
root = "."
narHash = "sha256-uKIWgjm98bQAYaNiMD/UOfwg55LWcAj2oC9AzSQuNBA="
entry = "main.bend"
[deps.ezhttp]
hash = "0x5e4e2a9db839a0214ace6923b04b685b"
git = "https://github.com/Emerging-Patterns/ezhttp"
rev = "a5279268547ee43b5c48b6c8ada235b4a4596f4c"
tag = "v0.6.0"
root = "ezhttp"
narHash = "sha256-Xn6zaCwV8mdIorktU04few1qfhCRobo16yF9H4osPRk="
entry = "ezhttp/main.bend"
[deps.eztoml]
hash = "0xd79254973edee82bcf56616220876efe"
git = "https://github.com/Emerging-Patterns/eztoml"
rev = "10c3079194db0d6adc9dfb908e877f785a442669"
tag = "v0.5.0"
root = "."
narHash = "sha256-oWGYok7TMYvBF1ctGYXZ6J10TRMcffDTrRNjgOH6qi0="
entry = "main.bend"
[tools]
[tools.bolt]
git = "https://github.com/Emerging-Patterns/bolt"
rev = "d5a67600a96ba423f2212bd661a30c1fba38eb55"
tag = "v1.9.0"
root = "."
narHash = "sha256-HmJ8J1xDshBdSWXIiEp48GZ9qHsm+bmpHw06ZWwcDVE="
